//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserDataBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup in progress..
        /// </summary>
        internal static string BackupInProgressStatus {
            get {
                return ResourceManager.GetString("BackupInProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BackupTargets {
            get {
                object obj = ResourceManager.GetObject("BackupTargets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string DecentralizeAUT {
            get {
                return ResourceManager.GetString("DecentralizeAUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DHA_Backup_Utility {
            get {
                object obj = ResourceManager.GetObject("DHA_Backup_Utility", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program backs data up to OneDrive.  However, you do not currently have an active network connection. You can still run the backup, and it will be queued for update to OneDrive next time you connect. You should NOT treat this backup as complete until you are connected back to the MHS network, and your OneDrive icon shows &apos;Up to Date&apos;..
        /// </summary>
        internal static string NoNetworkMessage {
            get {
                return ResourceManager.GetString("NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoNetworkStatus {
            get {
                return ResourceManager.GetString("NoNetworkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operations with a status of &apos;NoNewProfile&apos; cannot be competed until the program is launched for the first time..
        /// </summary>
        internal static string NoNewProfileMessage {
            get {
                return ResourceManager.GetString("NoNewProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need assistance setting up OneDrive, please contact GSC at 800-600-9332 or https://gsc.health.mil.
        /// </summary>
        internal static string NoOneDriveFolderMessage {
            get {
                return ResourceManager.GetString("NoOneDriveFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need assistance setting up OneDrive, please contact the DISA Service Desk at 844-DISA-HLP or https://help.disa.mil/gsd.
        /// </summary>
        internal static string NoOneDriveFolderMessageDISA {
            get {
                return ResourceManager.GetString("NoOneDriveFolderMessageDISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of User Data Management is intended for OneDrive only..
        /// </summary>
        internal static string NoOneDriveFolderStatus {
            get {
                return ResourceManager.GetString("NoOneDriveFolderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap offline_icon_19 {
            get {
                object obj = ResourceManager.GetObject("offline_icon_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OneDrive {
            get {
                object obj = ResourceManager.GetObject("OneDrive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onedrive_base {
            get {
                object obj = ResourceManager.GetObject("onedrive_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OneDriveError {
            get {
                object obj = ResourceManager.GetObject("OneDriveError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Microsoft OneDrive\OneDrive.exe.
        /// </summary>
        internal static string OneDriveExecutablePath {
            get {
                return ResourceManager.GetString("OneDriveExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to complete the backup, Outlook, Sticky Notes, AsUType and all browsers must be closed. Please ensure you have no unsaved work before continuing..
        /// </summary>
        internal static string ProcessCloseMessage {
            get {
                return ResourceManager.GetString("ProcessCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operations complete! Here are the results of each item:.
        /// </summary>
        internal static string RestoreResultMessage {
            get {
                return ResourceManager.GetString("RestoreResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SapphTools_BookmarkManager_Chromium {
            get {
                object obj = ResourceManager.GetObject("SapphTools_BookmarkManager_Chromium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SyncComplete2 {
            get {
                object obj = ResourceManager.GetObject("SyncComplete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync complete!.
        /// </summary>
        internal static string SyncCompleteMessage {
            get {
                return ResourceManager.GetString("SyncCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SyncInPrgress {
            get {
                object obj = ResourceManager.GetObject("SyncInPrgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bookmarks, sticky notes, Outlook signatures, and AsUType shortcuts (if extant) have been backed up to the Backup folder in your OneDrive. However, it is critical you do not log out, remove your CAC, reboot, or interrupt your network connection until sync is complete..
        /// </summary>
        internal static string SyncInProgressMessage {
            get {
                return ResourceManager.GetString("SyncInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync in progress..
        /// </summary>
        internal static string SyncInProgressStatus {
            get {
                return ResourceManager.GetString("SyncInProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync timed out.  This could be due to a slow connection, or due to one or more files blocking OneDrive from reporting a fully synced status.  Please check the status of OneDrive manually from the taskbar icon..
        /// </summary>
        internal static string SyncTimedOutMessage {
            get {
                return ResourceManager.GetString("SyncTimedOutMessage", resourceCulture);
            }
        }
    }
}
